/*
 * Created by Nils Druyen on 12-30-2021
 * Copyright © 2021 Nils Druyen. All rights reserved.
 */

package de.nilsdruyen.myboardgames.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF914c00)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdcc1)
val md_theme_light_onPrimaryContainer = Color(0xFF2f1500)
val md_theme_light_secondary = Color(0xFF006d42)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF91f7bd)
val md_theme_light_onSecondaryContainer = Color(0xFF002110)
val md_theme_light_tertiary = Color(0xFF9c4043)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd9d9)
val md_theme_light_onTertiaryContainer = Color(0xFF400007)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbf7)
val md_theme_light_onBackground = Color(0xFF1e1b16)
val md_theme_light_surface = Color(0xFFfffbf7)
val md_theme_light_onSurface = Color(0xFF1e1b16)
val md_theme_light_surfaceVariant = Color(0xFFf3dfd2)
val md_theme_light_onSurfaceVariant = Color(0xFF51443b)
val md_theme_light_outline = Color(0xFF847469)
val md_theme_light_inverseOnSurface = Color(0xFFf7f0e7)
val md_theme_light_inverseSurface = Color(0xFF33302a)

val md_theme_dark_primary = Color(0xFFffb779)
val md_theme_dark_onPrimary = Color(0xFF4e2600)
val md_theme_dark_primaryContainer = Color(0xFF6f3900)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdcc1)
val md_theme_dark_secondary = Color(0xFF75daa3)
val md_theme_dark_onSecondary = Color(0xFF003920)
val md_theme_dark_secondaryContainer = Color(0xFF005231)
val md_theme_dark_onSecondaryContainer = Color(0xFF91f7bd)
val md_theme_dark_tertiary = Color(0xFFffb3b2)
val md_theme_dark_onTertiary = Color(0xFF60131a)
val md_theme_dark_tertiaryContainer = Color(0xFF7d2a2e)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd9d9)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1e1b16)
val md_theme_dark_onBackground = Color(0xFFe9e2d9)
val md_theme_dark_surface = Color(0xFF1e1b16)
val md_theme_dark_onSurface = Color(0xFFe9e2d9)
val md_theme_dark_surfaceVariant = Color(0xFF51443b)
val md_theme_dark_onSurfaceVariant = Color(0xFFd6c3b6)
val md_theme_dark_outline = Color(0xFF9f8e82)
val md_theme_dark_inverseOnSurface = Color(0xFF1e1b16)
val md_theme_dark_inverseSurface = Color(0xFFe9e2d9)

val seed = Color(0xFFfcb67d)
val error = Color(0xFFba1b1b)
val Custom0 = Color(0xFF57b295)